fpath=($HOME/repos/dotfiles/zsh $fpath)
zstyle ':completion:*' completer _expand _complete _ignored _correct
zstyle :compinstall filename "$HOME/.zshrc"

autoload -Uz compinit promptinit
compinit
promptinit; prompt pure
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory autocd beep extendedglob notify prompt_subst
unsetopt nomatch
bindkey -v

## CUSTOM FUNCTIONS
# Install fzf
export FZF_DEFAULT_OPTS="
--extended-exact
--color fg:252,bg:233,hl:67,fg+:252,bg+:235,hl+:81
--color info:144,prompt:161,spinner:135,pointer:135,marker:118
"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

aws-ips () {
  aws --output text --region ap-southeast-1 ec2 describe-instances \
    --filters "Name=tag:Name,Values=${1}" | grep -i --color PRIVATEIPADDRESSES \
    | awk '{ print $4 }' | tr '\n' ' '
}

alias tf="terraform"

function sgtoname () {
  aws --profile grab ec2 describe-security-groups --output json \
    --group-id "$1" | jq ".SecurityGroups[0].GroupName"
}

## END CUSTOM FUNCTIONS

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh


